blacklist: [z00-001, z01-000, z01-000z, 01-010a, z01-010, z01-010b, z01-010c]
checkpoint_path: "./model_checkpoints/ConvNeXt"
data_path: "./raw_data/IAMonDB"

max_epochs: 50
batch_size: 16
img_height: 90
img_width: 1400
max_files: 0
max_seq_len: 480
max_text_len: 50
train_size: 0.85
vocab: ' _abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,.''-":()!'

gen_model_type: "Diffusion"
